# paths to targets to dock
# protDir - directory containing the protein(s)
# ligandDir - directory containing the ligand(s)
# outDir - location to save output to

pathInfo:
  protDir: "/home/nell/voidDock/receptors"
  ligandDir: "/home/nell/voidDock/ligands"
  outDir: "/home/nell/voidDock/outputs"

cpuInfo:
  totalCpuUsage: 16
  cpusPerRun: 16

dockingOrders:
  - protein: "lmr_heme_round_2"
    ligands: ["TPA", "TPA2"]
    mutatePocketToAla: False
    pocketResidues: 
      - CHAIN_ID: "A"
        RES_NAME: "GLN"
        RES_ID: 13
      - CHAIN_ID: "A"
        RES_NAME: "PHE"
        RES_ID: 203
      - CHAIN_ID: "A"
        RES_NAME: "ASN"
        RES_ID: 124

    keepResidues: 
      - CHAIN_ID: "A"
        RES_NAME: "ASN"
        RES_ID: 124

    flexibleResidues:
      - CHAIN_ID: "A"
        RES_NAME: "GLN"
        RES_ID: 13