# paths to targets to dock
# protDir - directory containing the protein(s)
# ligandDir - directory containing the ligand(s)
# outDir - location to save output to

pathInfo:
  protDir: "/home/esp/scriptDevelopment/voidDock/receptors"
  ligandDir: "/home/esp/scriptDevelopment/voidDock/ligands"
  outDir: "/home/esp/scriptDevelopment/voidDock/outputs"

cpuInfo:
  totalCpuUsage: 8
  cpusPerRun: 8

dockingOrders:
  - protein: "A0A0D2XFD3"
    ligands: ["FFF", "TPA"]
    pocketResidues: ["A:ALA:268", "A:SER:367", "A:GLY:233", "A:GLY:171"]
