# paths to targets to dock
# protDir - directory containing the protein(s)
# ligandDir - directory containing the ligand(s)
# outDir - location to save output to
# ligandOrdersCsv - csv file containing a list of [proteinID,ligandID] to dock
dockingTargetsInfo: 
  protDir: "/home/{username}/voidDock/receptors"
  ligandDir: "/home/{username}/voidDock/ligands"
  outDir: "/home/{username}/voidDock/outputs"
  ligandOrdersCsv: "/home/{username}/voidDock/docking_commands.csv"

# paths to MGLTools utilities
toolInfo:
  mglToolsDir: "/home/{username}/bin/mgltools_x86_64Linux2_1.5.7/MGLToolsPckgs"
  util24Dir: "/home/{username}/bin/mgltools_x86_64Linux2_1.5.7/MGLToolsPckgs/AutoDockTools/Utilities24"
