# paths to targets to dock
# protDir - directory containing the protein(s)
# ligandDir - directory containing the ligand(s)
# outDir - location to save output to

pathInfo:
  protDir: "/home/esp/scriptDevelopment/voidDock/receptors"
  ligandDir: "/home/esp/scriptDevelopment/voidDock/ligands"
  outDir: "/home/esp/scriptDevelopment/voidDock/outputs"

methodInfo:
  dockingMethod: "vina"
  # gninaExe: "/home/esp/bin/gnina/gnina"

cpuInfo:
  totalCpuUsage: 1
  cpusPerRun: 1

dockingOrders:
  - protein: "lmr_heme_round_2"
    ligands: ["TPA"]
    mutatePocketToAla: True
    pocketResidues: 
      - CHAIN_ID: "A"
        RES_NAME: "GLN"
        RES_ID: 13
      - CHAIN_ID: "A"
        RES_NAME: "PHE"
        RES_ID: 203
      - CHAIN_ID: "A"
        RES_NAME: "ASN"
        RES_ID: 124

    # keepResidues: 
    #   - CHAIN_ID: "A"
    #     RES_NAME: "ASN"
    #     RES_ID: 124

    # flexibleResidues:
    #   - CHAIN_ID: "A"
    #     RES_NAME: "GLN"
    #     RES_ID: 13